### PR TITLE
Switched from argparse to docopt

### PR DESCRIPTION
**Pull request by dbrgn**
In case you're interested, this PR replaces the builtin argparse module with the external docopt module.

http://docopt.org/
https://github.com/docopt/docopt

It makes it much simpler to create command line interfaces. You just edit the documentation in the module docstring, and the interface automatically adjusts.

Example (using pdb):

```
$ python kort2osm.py -d -v -c 10
> /home/danilo/Projects/kort-to-osm/kort2osm.py(56)<module>()
(Pdb) arguments
{'--count': '10',
 '--dry': True,
 '--help': False,
 '--quiet': False,
 '--verbose': True,
 '--version': False}
```

I couldn't really test it because I don't want to actually commit something to OSM, but the CLI interface should be equivalent.

### CODE REVIEW

**Comment by metaodi** [comment]
Thanks, I'll have a look at it. At first glance, it looks very good. I like the idea to generate the CLI from the docstring :wink:

**Comment by dbrgn** [comment]
It's _much_ easier to handle, as long as you don't need complicated data validation (which you could do with other libraries). It even supports subcommands à la git, as far as I know.

**Comment by metaodi** [comment]
Yeah, I saw the reference to ["schema"](https://github.com/halst/schema) as a possibility to validate the arguments. Maybe I will add that later.

**Comment by metaodi** [comment]
Looks good, thanks!

**Pull request merged**
